export const colorsOptions = [
  { key: 1, text: 'All', value: '*' },
  { key: 2, text: 'White', value: 'white' },
  { key: 3, text: 'Red', value: 'red' },
  { key: 4, text: 'Green', value: 'green' },
  { key: 5, text: 'Blue', value: 'blue' },
  { key: 6, text: 'Black', value: 'black' },
  { key: 7, text: 'Multicolor', value: 'multicolor' },
  { key: 8, text: 'Colorless', value: 'colorless' }
]

export const rarityOptions = [
  { key: 0, text: 'All', value: '*' },
  { key: 1, text: 'Common', value: 'common' },
  { key: 2, text: 'Uncommon', value: 'uncommon' },
  { key: 3, text: 'Rare', value: 'rare' },
  { key: 4, text: 'Mythic', value: 'mythic' }
]

export const orderOptions = [
  { key: 1, text: 'Released', value: 'released' },
  { key: 2, text: 'Usd', value: 'usd' },
  { key: 3, text: 'Tix', value: 'tix' },
  { key: 4, text: 'Euro', value: 'euro' },
  { key: 5, text: 'Cmc', value: 'cmc' },
  { key: 6, text: 'Edhrec', value: 'edhrec' },
  { key: 7, text: 'Penny', value: 'penny' },
  { key: 8, text: 'Name', value: 'name' },
  { key: 9, text: 'Set', value: 'set' },
  { key: 10, text: 'Rarity', value: 'rarity' },
  { key: 11, text: 'Color', value: 'color' },
  { key: 12, text: 'Power', value: 'power' },
  { key: 13, text: 'Toughness', value: 'toughness' },
  { key: 14, text: 'Artist', value: 'artist' },
  { key: 15, text: 'Review', value: 'review' }
]

export const uniqueOptions = [
  { key: 1, text: 'Cards', value: 'cards' },
  { key: 2, text: 'Arts', value: 'arts' },
  { key: 3, text: 'Prints', value: 'prints' }
]

export const powerOptions = [
  { key: 1, text: '*', value: '*' },
  { key: 2, text: '-1', value: '-1' },
  { key: 3, text: '?', value: '?' },
  { key: 4, text: '0', value: '0' },
  { key: 5, text: 'All', value: '∞' },
  { key: 6, text: '*²', value: '*²' },
  { key: 7, text: '.5', value: '.5' },
  { key: 8, text: '+0', value: '+0' },
  { key: 9, text: '+1', value: '+1' },
  { key: 10, text: '1', value: '1' },
  { key: 11, text: '1+*', value: '1+*' },
  { key: 12, text: '1.5', value: '1.5' },
  { key: 13, text: '+2', value: '+2' },
  { key: 14, text: '2', value: '2' },
  { key: 15, text: '2+*', value: '2+*' },
  { key: 16, text: '2.5', value: '2.5' },
  { key: 17, text: '+3', value: '+3' },
  { key: 18, text: '3', value: '3' },
  { key: 19, text: '3.5', value: '3.5' },
  { key: 20, text: '+4', value: '+4' },
  { key: 21, text: '4', value: '4' },
  { key: 22, text: '5', value: '5' },
  { key: 23, text: '6', value: '6' },
  { key: 24, text: '7', value: '7' },
  { key: 25, text: '8', value: '8' },
  { key: 26, text: '9', value: '9' },
  { key: 27, text: '10', value: '10' },
  { key: 28, text: '11', value: '11' },
  { key: 29, text: '12', value: '12' },
  { key: 30, text: '13', value: '13' },
  { key: 31, text: '15', value: '15' },
  { key: 32, text: '16', value: '16' },
  { key: 33, text: '18', value: '18' },
  { key: 34, text: '20', value: '20' },
  { key: 35, text: '99', value: '99' }
]

export const toughnessOptions = [
  { key: 1, text: '*', value: '*' },
  { key: 2, text: '-1', value: '-1' },
  { key: 3, text: '?', value: '?' },
  { key: 4, text: '0', value: '0' },
  { key: 5, text: 'All', value: '∞' },
  { key: 6, text: '*²', value: '*²' },
  { key: 7, text: '.5', value: '.5' },
  { key: 8, text: '+0', value: '+0' },
  { key: 9, text: '*+1', value: '*+1' },
  { key: 10, text: '1+*', value: '1+*' },
  { key: 11, text: '+1', value: '+1' },
  { key: 12, text: '1', value: '1' },
  { key: 13, text: '1.5', value: '1.5' },
  { key: 14, text: '+2', value: '+2' },
  { key: 15, text: '2', value: '2' },
  { key: 16, text: '2+*', value: '2+*' },
  { key: 17, text: '2.5', value: '2.5' },
  { key: 19, text: '+3', value: '+3' },
  { key: 20, text: '3', value: '3' },
  { key: 21, text: '3.5', value: '3.5' },
  { key: 22, text: '+4', value: '+4' },
  { key: 23, text: '4', value: '4' },
  { key: 24, text: '5', value: '5' },
  { key: 25, text: '6', value: '6' },
  { key: 26, text: '7', value: '7' },
  { key: 27, text: '7-*', value: '7-*' },
  { key: 28, text: '8', value: '8' },
  { key: 29, text: '9', value: '9' },
  { key: 30, text: '10', value: '10' },
  { key: 31, text: '11', value: '11' },
  { key: 32, text: '12', value: '12' },
  { key: 33, text: '13', value: '13' },
  { key: 34, text: '15', value: '15' },
  { key: 35, text: '16', value: '16' },
  { key: 36, text: '18', value: '18' },
  { key: 37, text: '20', value: '20' },
  { key: 38, text: '99', value: '99' }
]
